changelog:
  change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Maintenance
      labels:
        - chore
        - refactor
        - build
        - ci
        - dependencies
    - title: Other Changes
      labels:
        - "*"
